### ISSUE TITLE
Basefinder Crash

### ISSUE THREAD

**Issue by Jumima68** [etianl/Trouser-Streak#13]
Basefinder crashes after time.

**Comment by etianl** [comment]
In what circumstance did it crash? Just wandering around? I ask because I'd like to try to recreate it. Also if I do fix it, it will be in the 1.19.4 and 1.20.1 versions as maintaining 4 different versions is a bit much. Update your stuff lol

**Comment by etianl** [comment]
Oh yeah, also what did you decide to put in list7, and what number of blocks to detect for that list?

**Comment by Jumima68** [comment]
I flew around with an Elytra in 1.19.2 and put in List 7 Mob Spawners.

**Comment by etianl** [comment]
alrighty, so the thing was flagging the natural mob spawners too? I'm looking into this a bit now

**Comment by Jumima68** [comment]
Yes it is.
LIke dungeon spawners, mineshaft spawners.

**Comment by etianl** [comment]
I'm testing that now and am hoping to crash so I can debug it further

**Comment by Jumima68** [comment]
It also happens in newer version, just letting u know.

**Comment by etianl** [comment]
Might take a bit for me to fix it if I can, I still haven't crashed but I think I might just spam some mob spawners and see if that helps me force the crash

**Comment by etianl** [comment]
fuck wrong button, not complete

**Comment by Jumima68** [comment]
I was playing on donut.

**Comment by etianl** [comment]
oh yeah that thing is leaking your coords btw lol, delete the log if you want I saw what the error should be

**Comment by Jumima68** [comment]
I wasnt at the base.

**Comment by etianl** [comment]
alrighty I just managed to force the crash, so I can work from there. If you want to avoid the crash you might have to use the button to delete base data and not trace there until I work something out

**Comment by Jumima68** [comment]
I dont have Tracer on and I deleted it.

**Comment by Jumima68** [comment]
And the crash still comes.
But I can wait.

**Comment by etianl** [comment]
I think I got it fixed, now I just need to tweak the defaults for the blocks lists to eliminate a couple false positives, do some testing, then 0.5.9 comes. I even made another new module which wouldn't be available for 1.19.2 so your updating is made more worth it :D

**Comment by Jumima68** [comment]
Thank u!

**Comment by etianl** [comment]
Hopefully this update here fixes your crash. [Trouser-Streak 0.5.9](https://github.com/etianl/Trouser-Streak/releases/tag/v0.5.9)
If you have any more issues, please open a new one, and I appreciate your feedback
