### ISSUE TITLE
Version in fabric-mod.json does not match the release version

### ISSUE THREAD

**Issue by Application-maker** [etianl/Trouser-Streak#14]
The version in fabric-mod.json is 0.5.8 the current release version is 0.6.4

**Comment by etianl** [comment]
Where are you seeing this? I cannot find

**Comment by Application-maker** [comment]
Download trouser-streak release (mine is 0.6.4-1.20.1) extract it as an archive go to fabric.mod.json and check the "version" line, or just use multimc

**Comment by etianl** [comment]
now that's interesting, I'll look into that

**Comment by etianl** [comment]
I fixed it, and will post it when I push the next update. (soon)

**Comment by Application-maker** [comment]
Thanks i will close it on the next update

**Comment by etianl** [comment]
I finally posted that update. The version in the fabric mod json should be fixed. Please post any other issues or ideas if they ever arise
