### ISSUE TITLE
Option of disabling "Inventory Management"

### ISSUE THREAD

**Issue by denisapain** [etianl/Trouser-Streak#16]
It is very annoying for this addon to do this and not have a option to turn it off, if there is a option, please tell me where to find it!

**Comment by etianl** [comment]
what inventory management where? Using which module?

**Comment by denisapain** [comment]
No module is active but trouserstreak is putting my pickaxe out of my inv into my hotbar and it is annoying, this only happens when trouserstreak is installed

> what inventory management where? Using which module?

**Comment by etianl** [comment]
are you sure there are no modules on? The only ones that can do this that I rememberr right now in the trouser-streak are redstone nuker and the shulker dupe but only if the modules are on

**Comment by denisapain** [comment]
> are you sure there are no modules on? The only ones that can do this that I rememberr right now in the trouser-streak are redstone nuker and the shulker dupe but only if the modules are on

I'm sure, nothing is on, maybe a bug in TS that makes one of those modules always active?

**Comment by etianl** [comment]
try turning the redstone nuker module on then off again. Thats the only thing that can create the bug which you describe. I have never actually seen the bug occur so it's really hard for me to say what's going on. I'll try to look into it later today if I get some time

**Comment by etianl** [comment]
I am not able to reproduce this bug
