### ISSUE TITLE
lokiiez skidded the fireball thing from me please update in the readme <3

### ISSUE THREAD

**Issue by TaxEvasiqn** [etianl/Trouser-Streak#2]

**Comment by etianl** [comment]
Sorry, which fireball thing?

**Comment by etianl** [comment]
I updated the readme to say that FireBallRain+ was from Allahhack, but the code was pulled from the griefwaffen page. The other fireball thing isn't yours too right?

**Comment by TaxEvasiqn** [comment]
i yoinked a bit from coffee in that one
