### ISSUE TITLE
antivirus and fabric both flag as virus

### ISSUE THREAD

**Issue by 3xyy** [etianl/Trouser-Streak#36]
![image](https://github.com/etianl/Trouser-Streak/assets/77691604/3212032a-9994-433f-bbdb-191d3760a715)
![image](https://github.com/etianl/Trouser-Streak/assets/77691604/a6d30f21-57b8-46e5-a038-a735e0de8f3e)

**Comment by etianl** [comment]
well that's strange. If you're really concerned feel free to look at all the source and build it yourself. I don't even know how to virus someone to be honest

**Comment by 3xyy** [comment]
false positive, code looks clean, have fun griefing 😄

**Comment by 3xyy** [comment]
\
