### ISSUE TITLE
Kicked for "Illegal Characters in chat" after running AutoScoreboard, AutoTitle and AutoDisplay

### ISSUE THREAD

**Issue by gatesbydude** [etianl/Trouser-Streak#39]
Kicked immediately after activating AutoScoreboard, AutoTitle and AutoDisplay for posting "illegal characters".
Latest TrouserStreak ver.
Meteor v0.5.7-2105

**Comment by etianl** [comment]
I have been doing some testing and I think your issue may be server-specific. I have not been able to trigger it myself yet

**Comment by gatesbydude** [comment]
Yeah in the end it was a user issue. one of my strings really had an illegal character

**Comment by zyrafaq** [comment]
> Yeah in the end it was a user issue. one of my strings really had an illegal character

For the next time consider producing your issues on default trouser settings (unless a setting or combination of them isn't working)
