### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by IF-desu** [etianl/Trouser-Streak#4]
MC version:1.19.2
Mod version:The latest v0.2.8 for 1.19.2
Fabric Version:0.14.11
Log:
[crash-2023-01-11_14.30.13-client.txt](https://github.com/etianl/Trouser-Streak/files/10390425/crash-2023-01-11_14.30.13-client.txt)
[latest.log](https://github.com/etianl/Trouser-Streak/files/10390434/latest.log)

**Comment by etianl** [comment]
I'll be honest with you I have never looked at a crash log before. It does appear that maybe betterscaffold is the issue, and that the crash is happening on loading a world? If that's the case try pressing right shift in the main menu and disable any Trouser modules before loading the world. Could you provide more details as to the circumstances upon which the crash happens? Are you able to replicate the crash? Better Scaffold appears to work with the client and other mods that I am using

**Comment by IF-desu** [comment]
I launch the game and the game crashed without entering loading screen,but i will try to remove betterscaffold

**Comment by IF-desu** [comment]
And it seems that i doesnt install betterscaffold :(

**Comment by dlfnn** [comment]
> 

Betterscaffold might very likely be related to mod MeteorClient. Furthur more, most info's the crash report provides is meteor-related, hence I'd recommend try load the mod without meteor.

**Comment by dlfnn** [comment]
> java.lang.NoSuchMethodError: 'meteordevelopment.meteorclient.settings.ColorSetting$Builder meteordevelopment.meteorclient.settings.ColorSetting$Builder.defaultValue(meteordevelopment.meteorclient.utils.render.color.SettingColor)'

**Comment by dlfnn** [comment]
Maybe try update meteor to latest version 0.5.2

**Comment by etianl** [comment]
Actually, for the 1.19.2 version of trouser streak the full release of meteor 0.5.1 should be used. The latest dev build of meteor (0.5.2) should be used if you want to use the 1.19.3 version of Trouser

**Comment by IF-desu** [comment]
I update the meteor client verison 0.5.1-1661 to version0.5.1 full release,but it doesn't work :(
[latest.log](https://github.com/etianl/Trouser-Streak/files/10410242/latest.log)

**Comment by IF-desu** [comment]
it's a pity that all my mod's versions inlcuded fabricapi are too old ,I tried for a whole day but it still doesn't works :(
I also installed 1.19.2 and tried it,luckily, it worked

**Comment by etianl** [comment]
You'll have to find the latest versions of the mods you like for Minecraft version 1.19.2. You say "luckily, it worked". No more issue?
