### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by Nuclearpotato69** [etianl/Trouser-Streak#42]
PLEASE add skibidi toilet esp where the player turns into a toilet and their head comes out of it

**Comment by veronoicc** [comment]
+1

**Comment by etianl** [comment]
there is an open discussion for feature requests. This one I will choose to not do sorry mates
https://github.com/etianl/Trouser-Streak/discussions/10

**Comment by GoldenStack** [comment]
> there is an open discussion for feature requests. This one I will choose to not do sorry mates #10

please reconsider

**Comment by nikolan123** [comment]
> > there is an open discussion for feature requests. This one I will choose to not do sorry mates #10
> 
> please reconsider

yes pls

**Comment by veronoicc** [comment]
> there is an open discussion for feature requests. This one I will choose to not do sorry mates #10

Maybe gibe this another thought? It seems like its pretty heavily requested
