### ISSUE TITLE
[feature request] make boom+ be able to shoot falling blocks like airstrike+

### ISSUE THREAD

**Issue by reeeboy45** [etianl/Trouser-Streak#43]
I wanna shoot anvils at villagers

**Comment by etianl** [comment]
Lol sounds like it'd be fun, I'll do this when I get some spare time. Don't expect it soon though I am pretty busy but I will add it for sure at some point

**Comment by etianl** [comment]
Next release I will add this lol, I just realized it was super easy to add to Boom+

**Comment by etianl** [comment]
It doesn't harm the villagers in my testing to throw anvils at them sadly

**Comment by reeeboy45** [comment]
thanks though, looking forward to using it

**Comment by etianl** [comment]
I'm just testing out a new module then I will post a release today or tomorrow :)
