### ISSUE TITLE
feature request - skybuilder

### ISSUE THREAD

**Issue by Grubbyr** [etianl/Trouser-Streak#45]
pretty obvious, like an obsidian sky maker from 2b2t

customization
size (100x by 100x)
block whitelist
could add more but its basically it

also have a tiny thing in the center of the screen saying
"estimated blocks [number]"

**Comment by etianl** [comment]
Have you tried the BetterScaffold module?

**Comment by etianl** [comment]
I have decided I probably will not do this as it's not super useful for griefing
