### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by reizi74** [etianl/Trouser-Streak#46]
add diagonal tunnels like this one to Hole/Tunnel/Stairs ESP
![рек](https://github.com/user-attachments/assets/cbb2bbd3-934d-45d0-896c-b3649f4e2f94)

**Comment by etianl** [comment]
Lol alright, I'll look into it later

**Comment by etianl** [comment]
Oh right I just remembered I have to find a youtuber to grief before I can get on more coding. After that I will do it (I am late on making a new video for me youtube)

**Comment by etianl** [comment]
please check out the new release :)
https://github.com/etianl/Trouser-Streak/releases/tag/v1.2.3

**Comment by reizi74** [comment]
yoooo that's crazy

**Comment by etianl** [comment]
If you get any other neat ideas feel free to let me know. If it will aid base finding and/or griefing I add it in :)
