### ISSUE TITLE
Kicked for Command spam

### ISSUE THREAD

**Issue by zz32k** [etianl/Trouser-Streak#51]
On a lot of servers, you get kicked when doing multiple commands in quick succession. This causes some modules to not work at all, such as AutoTitle, AutoDisplay, AutoCommand(when doing multiple commands) and AutoScoreboard. Adding a way add delays like the one in HandOfGod would probably fix this.

**Comment by etianl** [comment]
Will look into it when I have time, thank you for bringing this to my attention

**Comment by etianl** [comment]
https://github.com/etianl/Trouser-Streak/pull/67
DedicatedDev fixed it for us :D 
https://github.com/DedicateDev
