### ISSUE TITLE
I just wanna say What the fuck.

### ISSUE THREAD

**Issue by FooFieOwO** [etianl/Trouser-Streak#53]
pwn.noobs.trouserstreak.modules.SuperInstaMine

delete and recode.

**Comment by kybe236** [comment]
<img width="769" height="500" alt="Image" src="https://github.com/user-attachments/assets/a13d7f27-4128-46bf-9f5e-9390d08bed89" />

**Comment by etianl** [comment]
Mountains of Java Inc.
